Create api endpoints
Ugboaja-Uchechi/hello-rails-back-end pull request #3
Opened 2022-03-29 19:55 UTC by Ugboaja-Uchechi

### Project Requirements

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).

2022-03-29 21:00 UTC, DeliceLydia requested changes
## Hi @Ugboaja-Uchechi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights are:
- Followed git workflow
- No linter errors


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-03-29 21:00 UTC, DeliceLydia commented on config/routes.rb
> +      get 'random', to: 'greetings#random'
- [x] I am not able to fetch different greetings on the frontend, check if errors are not coming from not setting up `cors` well
![cors](https://user-images.githubusercontent.com/44745855/160705967-9a6334b9-d33f-496d-a433-be82272ed290.png)

2022-03-30 09:26 UTC, rloterh requested changes
Hi Stephanie, 

You did great on this project, and for making the changes requested in the previous review(s)! 👏👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- No linter errors

## Required Changes ♻️
_Kindly check the comments below this review. Please take your time to carefully improve aspects outlined in the previous code review(s), and please check to see that the changes implemented are working as intended._


<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 09:26 UTC, rloterh commented on config/routes.rb
> +      get 'random', to: 'greetings#random'
- [ ] Kindly endeavor to install and configure CORS gems so as to resolve this error, as recommended in the previous code review.

**Error:**
![image](https://user-images.githubusercontent.com/12745474/160798002-b6108163-2f74-4030-af5a-b0acdb24347b.png)

2022-03-30 12:19 UTC, Emmyn5600 approved these changes
Hi @Ugboaja-Uchechi 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

![image](https://user-images.githubusercontent.com/55635977/160832583-011442f9-a82b-4fde-9d92-36c00dc76e8b.png)

![image](https://user-images.githubusercontent.com/55635977/160832664-d91401a6-cf66-4cf2-90bd-04b387c03b4f.png)

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

- [ ] N/A

#### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
#### _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-30 12:24 UTC, merged